name: test

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: setup_conda
      run: |
        export conda_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        
        wget $conda_url -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda install -c conda-forge mamba
        
        export toolchain=clangxx_osx-64
        
        mamba create -q -n test-environment -c conda-forge -c bioconda -y meson clang $toolchain samtools
       
    - name: setup_meson
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        env CC=clang CXX=clang MACOSX_DEPLOYMENT_TARGET=10.10 meson setup --buildtype=release --prefix=$(pwd)/app/PretextView.app --bindir=Contents/MacOS --unity on builddir
      
    - name: meson_compile
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        cd builddir
        meson compile
    
    - name: meson_test
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        cd builddir
        meson test
